import Head from "next/head";
import Image from "next/image";
import Banners from "../components/Banners";
import CategoriesSection from "../components/Categories/CategoriesSection";
import Features from "../components/Features";
import Layout from "../components/Layout";
import TopBanner from "../components/Slider/Slider";
/* import styles from "../styles/Home.module.css"; */
import Demo from "./Demo/Demo";
import ProductGroupSection from './../components/ProductGroup/ProductGroupSection/index';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <TopBanner />
        <Features />
        <Banners />
        <CategoriesSection />
        <ProductGroupSection />
      </Layout>

      <footer></footer>
    </div>
  );
}
